First commit for temporary branch

diff --git a/script b/script
--- a/script
+++ b/script
@@ -19,15 +19,17 @@ do
 done < $webpage_input_dir
 
 # Load all the webpage entries from the webpages_queue file to an array
-webpages_queue_array=()
+initial_webpages_queue_array=()
 
 while IFS= read -r file_entry
 do
-	webpages_queue_array+=("$file_entry")
+	initial_webpages_queue_array+=("$file_entry")
 	
 done < $webpages_queue_dir
 
-
+# final_webpages_queue_array will be used to store the refreshed and up-to-date
+# data of the initial entries saved in initial_webpages_queue_array.
+final_webpages_queue_array=()
 
 # Iterate through all the webpage entries of the webpages_input_array,
 # checking the webpages one by one
@@ -41,46 +43,117 @@ done < $webpages_queue_dir
 for input_url in "${webpages_input_array[@]}"
 do
 	
-	# Check whether the given url already exists in the webpages_queue_array
+	# Check whether the given url already exists in the initial_webpages_queue_array
 	found_url=0
 	
-	for queue_entry in "${webpages_queue_array[@]}"
+	for queue_entry in "${initial_webpages_queue_array[@]}"
 	do
-		# get the webpage url and the md5sum seperately
+		# get the saved webpage url, md5sum and status seperately
 		entry_data=($queue_entry)
 		queue_url=${entry_data[0]}
 		url_md5sum=${entry_data[1]}
+		url_status=${entry_data[2]}
 		
 		if [ "$input_url" = "$queue_url" ]; then
-			
+			# Found the target url in the url_queue"
 			echo "Found the target url in the url_queue"
 			found_url=1
+			
+			# ping the target url to check if it's reachable
+			ping -c 1 "$input_url"
+		
+			# $? gets the exit status of the last executed command/function/program
+			target_reachable=$?
+			
+			if [ $target_reachable -eq 0 ]; then
+				# target url was found to be reachable!
+				
+				current_status="REACHABLE"
+				
+				# *** Chech the webpage for changes ***
+				# Download the currect webpage's md5sum and compare it 
+				# to the stored md5sum for this webpage.
+				current_md5sum=($(wget -q -O - $input_url | md5sum))
+				
+				
+				if [ "$url_md5sum" != "$current_md5sum" ] || [ "$url_status" = "UNREACHABLE" && "$current_status" = "REACHABLE"]; then
+					# the webpage HAS changed
+					# the webpage's md5sum we retrieved from the file is different compared to the one we generated now, so we conclude the webpage has changed
+					# or
+					# target was saved as UNREACHABLE, but during the last check was found to be REACHABLE, so we assume the webpage has changed
 
-			# *** Chech the webpage for changes ***
-			# Download the currect webpage's md5sum and compare it 
-			# to the stored md5sum for this webpage.
-			current_md5sum=($(wget -q -O - $input_url | md5sum))
-
-			if [ "$url_md5sum" != "$current_md5sum" ]; then
-				# The webpage has changed
-				echo "Detected changes in the given webpage"
-				echo $queue_url
+					echo "Detected changes in the given webpage:"
+					echo $queue_url
+					
+					# add the changed webpage's url and md5sum as a new entry to the final_webpages_queue_array
+					# (update the webpage's md5sum number)
+					final_webpages_queue_array+=("$input_url $current_md5sum $current_status")
+				
+				else 
+					# the webpage has not changed, so we simply add it to our final_webpages_queue_array
+					final_webpages_queue_array+=("$input_url $url_md5sum $url_status")
+			
+				fi
+				
+			
+			else
+				# target url was found to be unreachable
+				# add the unreachable webpage's url and (old) md5sum as a new entry to the final_webpages_queue_array
+				current_status="UNREACHABLE"
+				final_webpages_queue_array+=("$input_url $url_md5sum $current_status")
+				
 			fi
+
 				
 		fi
 		
 	done
 	
 	if [ $found_url = 0 ]; then
+		# Target url was NOT found in the url_queue
 		echo "Target url was NOT found in the url_queue"
+		
+		# ping the target url to check if it's reachable
+		ping -c 1 "$input_url"
+		
+		# $? gets the exit status of the last executed command/function/program
+		target_reachable=$?
+		
+		if [ $target_reachable -eq 0 ]; then
+			# target url was found to be reachable!
+			
+			# remove the http:// or https:// from the url so that we only keep the domain, ex 
+			# "http://www.example.com/somedir/someotherdir/index.html" ---> "
+			
+			
+			# ??????????????????
+			
+			
+			
+			# generate the webpage's md5sum
+			url_md5sum=($(wget -q -O - $input_url | md5sum))
+			
+			# status indicates whether we were able to ping the webpage during our last attempt
+			status="REACHABLE"
 
-		# generate the webpage's md5sum
-		url_md5sum=($(wget -q -O - $input_url | md5sum))
+			# add the webpage's url and md5sum as a new entry to the final_webpages_queue_array
+			final_webpages_queue_array+=("$input_url $url_md5sum $status")
 
-		# add the webpage's url and md5sum as a new entry to the webpages_queue_array
-		webpages_queue_array+=("$input_url $url_md5sum")
+			echo "$input_url INIT"
+		else
+			# target url was found to be unreachable
+			echo "$input_url FAILED"
+			
+			# status indicates whether we were able to ping the webpage during our last attempt
+			status="UNREACHABLE"
+			
+			url_md5sum="------------------"
+			
+			# add the webpage's url and (empty) md5sum as a new entry to the final_webpages_queue_array
+			final_webpages_queue_array+=("$input_url $url_md5sum $status")
+			
+		fi
 
-		echo "$input_url INIT"
 	fi
 	
 done
@@ -88,8 +161,8 @@ done
 # Empty the webpages_queue file
 > $webpages_queue_dir
 
-# Save the current webpages_queue_array state to the webpages_queue file
-for queue_entry in "${webpages_queue_array[@]}"
+# Save the current initial_webpages_queue_array state to the webpages_queue file
+for queue_entry in "${final_webpages_queue_array[@]}"
 do
 	#echo "mpika3-------------------"
 	#echo $queue_entry
